function registry = physio4all_example_registry()
%PHYSIO4ALL_EXAMPLE_REGISTRY Return canonical example dataset metadata.

registry = [ ...
    struct(id="openneuro_ds004808_brainhack23", mnemonic="brainhack23", ...
        source="OpenNeuro", accession="ds004808", snapshot="1.0.0", ...
        shortName="BrainHack 2023", ...
        authors="BrainHack 2023 PhysIO workshop", ...
        purpose="Brainstem fMRI with Siemens physiology", ...
        description="OpenNeuro ds004808 imaging plus OSF physiology " + ...
        "from the BrainHack 2023 PhysIO workshop"), ...
    struct(id="openneuro_ds004645_fastfmri", mnemonic="fastfmri", ...
        source="OpenNeuro", accession="ds004645", snapshot="1.0.0", ...
        shortName="Fast fMRI", authors="Lewis et al.", ...
        purpose="7T fast resting-state fMRI with BIDS physiology", ...
        description="OpenNeuro ds004645 7T resting-state fMRI with " + ...
        "BIDS physiology"), ...
    ];
end
