function matlabbatch = build_physio_batch(runInfo, preprocessOutputs, ...
        example, outputFolder)
%BUILD_PHYSIO_BATCH Build a PhysIO SPM batch for one fMRI run.

arguments
    runInfo (1,1) struct
    preprocessOutputs (1,1) struct
    example (1,1) struct
    outputFolder {mustBeTextScalar}
end

settings = example.physio;
outputFolder = string(outputFolder);
prefix = sprintf("%s_task-%s_run-%02d", runInfo.subjectID, ...
    runInfo.taskName, runInfo.runNumber);

matlabbatch{1}.spm.tools.physio.save_dir = cellstr(outputFolder);
matlabbatch{1}.spm.tools.physio.write_bids.bids_step = 4;
matlabbatch{1}.spm.tools.physio.write_bids.bids_dir = {""};
matlabbatch{1}.spm.tools.physio.write_bids.bids_prefix = prefix;
matlabbatch{1}.spm.tools.physio.log_files.vendor = char(settings.vendor);
matlabbatch{1}.spm.tools.physio.log_files.cardiac = ...
    cellstr(runInfo.cardiacFile);
matlabbatch{1}.spm.tools.physio.log_files.respiration = ...
    cellstr(runInfo.respirationFile);
matlabbatch{1}.spm.tools.physio.log_files.scan_timing = ...
    cellstr(runInfo.scanTimingFile);
matlabbatch{1}.spm.tools.physio.log_files.sampling_interval = [];
matlabbatch{1}.spm.tools.physio.log_files.relative_start_acquisition = 0;
matlabbatch{1}.spm.tools.physio.log_files.align_scan = ...
    char(settings.alignScan);

matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.Nslices = ...
    runInfo.nSliceEvents;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.NslicesPerBeat = [];
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.TR = ...
    runInfo.repetitionTime;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.Ndummies = 0;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.Nscans = ...
    runInfo.nVolumes;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.onset_slice = ...
    runInfo.onsetSlice;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.time_slice_to_slice = [];
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.Nprep = [];
matlabbatch{1}.spm.tools.physio.scan_timing.sync.scan_timing_log = ...
    struct([]);

matlabbatch{1}.spm.tools.physio.preproc.cardiac.modality = ...
    char(settings.cardiacModality);
matlabbatch{1}.spm.tools.physio.preproc.cardiac.filter.no = struct([]);
matlabbatch{1}.spm.tools.physio.preproc.cardiac.initial_cpulse_select. ...
    auto_matched.min = 0.4;
matlabbatch{1}.spm.tools.physio.preproc.cardiac.initial_cpulse_select. ...
    auto_matched.file = "initial_cpulse_kRpeakfile.mat";
matlabbatch{1}.spm.tools.physio.preproc.cardiac.initial_cpulse_select. ...
    auto_matched.max_heart_rate_bpm = 90;
matlabbatch{1}.spm.tools.physio.preproc.cardiac. ...
    posthoc_cpulse_select.off = struct([]);
matlabbatch{1}.spm.tools.physio.preproc.respiratory.filter.passband = ...
    [0.01 2];
matlabbatch{1}.spm.tools.physio.preproc.respiratory.despike = false;

matlabbatch{1}.spm.tools.physio.model.output_multiple_regressors = ...
    "multiple_regressors.txt";
matlabbatch{1}.spm.tools.physio.model.output_physio = "physio.mat";
matlabbatch{1}.spm.tools.physio.model.orthogonalise = "none";
matlabbatch{1}.spm.tools.physio.model. ...
    censor_unreliable_recording_intervals = false;
matlabbatch{1}.spm.tools.physio.model.retroicor.yes.order.c = ...
    settings.cardiacOrder;
matlabbatch{1}.spm.tools.physio.model.retroicor.yes.order.r = ...
    settings.respiratoryOrder;
matlabbatch{1}.spm.tools.physio.model.retroicor.yes.order.cr = ...
    settings.interactionOrder;
matlabbatch{1}.spm.tools.physio.model.rvt.yes.method = ...
    char(settings.rvtMethod);
matlabbatch{1}.spm.tools.physio.model.rvt.yes.delays = ...
    settings.rvtDelays;
matlabbatch{1}.spm.tools.physio.model.hrv.yes.delays = ...
    settings.hrvDelays;
matlabbatch{1}.spm.tools.physio.model.noise_rois.no = struct([]);
matlabbatch{1}.spm.tools.physio.model.movement.yes. ...
    file_realignment_parameters = cellstr(preprocessOutputs.motionFile);
matlabbatch{1}.spm.tools.physio.model.movement.yes.order = ...
    settings.movementOrder;
matlabbatch{1}.spm.tools.physio.model.movement.yes.censoring_method = ...
    char(settings.movementCensoringMethod);
matlabbatch{1}.spm.tools.physio.model.movement.yes.censoring_threshold = ...
    settings.movementCensoringThreshold;
matlabbatch{1}.spm.tools.physio.model.other.no = struct([]);

matlabbatch{1}.spm.tools.physio.verbose.level = 2;
matlabbatch{1}.spm.tools.physio.verbose.fig_output_file = ...
    "physio.fig";
matlabbatch{1}.spm.tools.physio.verbose.use_tabs = false;

end
